[workspace]
resolver = "2"

members = [
    "aegir_game", 
    "aegir_lib", 
    "aegir_macros", 
    "tools/ci"
]

default-members = ["aegir_game","aegir_lib"]

# Enable max dependenacy optimizations without impacting release compiles
[profile.dev.package."*"]
opt-level = 3